/**
 * omp 运行时配置定义
 * 根据 packages/coding-agent/src/config/settings-schema.ts 提取
 * 用于后台管理界面的配置下拉选择
 */

/** 配置值选项 */
export interface ConfigValueOption {
  value: string
  label: string
  description?: string
}

/** 配置项定义 */
export interface ConfigItemDef {
  key: string
  label: string
  description: string
  type: 'boolean' | 'enum' | 'number' | 'string'
  values?: ConfigValueOption[]
  defaultValue?: string | boolean | number | null
}

/**
 * omp 支持的运行时配置项列表
 * 按功能分组排序
 */
export const OMP_CONFIG_DEFINITIONS: ConfigItemDef[] = [
  // ==================== 核心 ====================
  {
    key: 'model.active',
    label: '当前激活模型',
    description: '当前激活的模型配置（JSON 对象，包含 api、apiKey、baseUrl、modelId、provider 等字段）。最高优先级热覆盖，OMP 进程启动时读取',
    type: 'string',
    defaultValue: null,
  },
  {
    key: 'omp.flags.approval-mode',
    label: '工具审批模式',
    description: '后端传给 OMP 进程的 --approval-mode 标志。always-ask=仅自动批准只读工具；write=自动批准读写工具；yolo=自动批准所有工具',
    type: 'enum',
    values: [
      { value: 'always-ask', label: '始终询问', description: '自动批准只读工具，确认写/执行工具' },
      { value: 'write', label: '写入', description: '自动批准读写工具，确认执行工具' },
      { value: 'yolo', label: 'Yolo', description: '自动批准所有工具' },
    ],
    defaultValue: 'yolo',
  },
  {
    key: 'omp.flags.thinking',
    label: '思考级别（标志）',
    description: '后端传给 OMP 进程的思考级别标志',
    type: 'enum',
    values: [
      { value: 'minimal', label: '最低', description: '最少推理' },
      { value: 'low', label: '低', description: '轻量推理' },
      { value: 'medium', label: '中', description: '适中推理' },
      { value: 'high', label: '高', description: '深度推理' },
      { value: 'xhigh', label: '极高', description: '最大推理' },
    ],
    defaultValue: 'medium',
  },
  {
    key: 'omp.flags.tools',
    label: '启用的工具列表',
    description: '后端传给 OMP 进程的工具白名单（JSON 数组，如 ["read","edit","write","bash","grep","find"]）。留空使用默认全部工具',
    type: 'string',
    defaultValue: null,
  },
  {
    key: 'vault.apiKey',
    label: 'Vault API Key',
    description: '通过 --api-key 传给 OMP 进程的 API 密钥。未设置时回退到 OMP_API_KEY 环境变量',
    type: 'string',
    defaultValue: null,
  },
  {
    key: 'symbolPreset',
    label: '符号预设',
    description: '图标和符号的字形集（Unicode、Nerd Font 或 ASCII）',
    type: 'enum',
    values: [
      { value: 'unicode', label: 'Unicode', description: '标准符号（默认）' },
      { value: 'nerd', label: 'Nerd Font', description: '需要 Nerd Font' },
      { value: 'ascii', label: 'ASCII', description: '最大兼容性' },
    ],
    defaultValue: 'unicode',
  },
  {
    key: 'display.smoothStreaming',
    label: '平滑流式输出',
    description: '在文本块到达时平滑显示助手文本和工具输入',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'display.showTokenUsage',
    label: '显示 Token 使用',
    description: '在助手消息上显示每轮 token 使用量',
    type: 'boolean',
    defaultValue: false,
  },

  // ==================== 模型 ====================
  {
    key: 'defaultThinkingLevel',
    label: '思考级别',
    description: '支持思考的模型的推理深度',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: '根据任务难度自动选择' },
      { value: 'minimal', label: '最低', description: '最少推理' },
      { value: 'low', label: '低', description: '轻量推理' },
      { value: 'medium', label: '中', description: '适中推理' },
      { value: 'high', label: '高', description: '深度推理（默认）' },
    ],
    defaultValue: 'high',
  },
  {
    key: 'hideThinkingBlock',
    label: '隐藏思考块',
    description: '在助手响应中隐藏思考块',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'repeatToolDescriptions',
    label: '重复工具描述',
    description: '在系统提示中渲染完整工具描述而非工具名列表',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'includeModelInPrompt',
    label: '在提示中包含模型',
    description: '在系统提示中显示活动模型标识符',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'temperature',
    label: 'Temperature',
    description: '采样温度（0=确定性，1=创造性，-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '0', label: '0', description: '确定性' },
      { value: '0.2', label: '0.2', description: '专注' },
      { value: '0.5', label: '0.5', description: '平衡' },
      { value: '0.7', label: '0.7', description: '创造性' },
      { value: '1', label: '1', description: '最大多样性' },
    ],
    defaultValue: -1,
  },
  {
    key: 'topP',
    label: 'Top P',
    description: '核采样截断值（0-1，-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '0.1', label: '0.1', description: '非常专注' },
      { value: '0.3', label: '0.3', description: '专注' },
      { value: '0.5', label: '0.5', description: '平衡' },
      { value: '0.9', label: '0.9', description: '广泛' },
      { value: '1', label: '1', description: '无核过滤' },
    ],
    defaultValue: -1,
  },
  {
    key: 'topK',
    label: 'Top K',
    description: '从 top-K token 中采样（-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '1', label: '1', description: '贪婪 top token' },
      { value: '20', label: '20', description: '专注' },
      { value: '40', label: '40', description: '平衡' },
      { value: '100', label: '100', description: '广泛' },
    ],
    defaultValue: -1,
  },
  {
    key: 'minP',
    label: 'Min P',
    description: '最小概率阈值（0-1，-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '0.01', label: '0.01', description: '非常宽松' },
      { value: '0.05', label: '0.05', description: '平衡' },
      { value: '0.1', label: '0.1', description: '严格' },
    ],
    defaultValue: -1,
  },
  {
    key: 'presencePenalty',
    label: '存在惩罚',
    description: '引入已存在 token 的惩罚（-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '0', label: '0', description: '无惩罚' },
      { value: '0.5', label: '0.5', description: '轻微新颖性' },
      { value: '1', label: '1', description: '鼓励新颖性' },
      { value: '2', label: '2', description: '强新颖性' },
    ],
    defaultValue: -1,
  },
  {
    key: 'repetitionPenalty',
    label: '重复惩罚',
    description: '重复 token 的惩罚（-1=提供商默认）',
    type: 'enum',
    values: [
      { value: '-1', label: '默认', description: '使用提供商默认值' },
      { value: '0.8', label: '0.8', description: '允许重复' },
      { value: '1', label: '1', description: '无惩罚' },
      { value: '1.1', label: '1.1', description: '轻微惩罚' },
      { value: '1.2', label: '1.2', description: '平衡' },
      { value: '1.5', label: '1.5', description: '强惩罚' },
    ],
    defaultValue: -1,
  },
  {
    key: 'serviceTier',
    label: '服务级别',
    description: '处理优先级提示（none=省略）',
    type: 'enum',
    values: [
      { value: 'none', label: '无', description: '省略 service_tier 参数' },
      { value: 'auto', label: '自动', description: '使用提供商默认级别（OpenAI）' },
      { value: 'default', label: '默认', description: '标准优先级处理（OpenAI）' },
      { value: 'flex', label: 'Flex', description: '弹性容量级别（OpenAI）' },
      { value: 'scale', label: 'Scale', description: 'Scale Tier 额度（OpenAI）' },
      { value: 'priority', label: '优先', description: '所有支持提供商的优先级' },
    ],
    defaultValue: 'none',
  },
  {
    key: 'fastModeScope',
    label: '快模式范围',
    description: '/fast on 目标的提供商',
    type: 'enum',
    values: [
      { value: 'both', label: '两者', description: '所有支持提供商的优先级' },
      { value: 'openai', label: '仅 OpenAI', description: '仅 OpenAI/OpenAI-Codex 请求' },
      { value: 'claude', label: '仅 Claude', description: '仅 Anthropic Claude 请求' },
    ],
    defaultValue: 'both',
  },
  {
    key: 'retry.maxRetries',
    label: '重试次数',
    description: 'API 错误时的最大重试次数',
    type: 'enum',
    values: [
      { value: '1', label: '1 次重试' },
      { value: '2', label: '2 次重试' },
      { value: '3', label: '3 次重试' },
      { value: '5', label: '5 次重试' },
      { value: '10', label: '10 次重试' },
    ],
    defaultValue: 10,
  },
  {
    key: 'retry.modelFallback',
    label: '重试模型回退',
    description: '允许重试恢复切换到配置的回退模型',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'retry.fallbackRevertPolicy',
    label: '回退恢复策略',
    description: '何时返回主模型',
    type: 'enum',
    values: [
      { value: 'cooldown-expiry', label: '冷却期结束', description: '抑制窗口结束后返回' },
      { value: 'never', label: '从不', description: '停留在回退模型直到手动更改' },
    ],
    defaultValue: 'cooldown-expiry',
  },

  // ==================== 交互 ====================
  {
    key: 'steeringMode',
    label: '引导模式',
    description: '代理工作时如何处理排队消息',
    type: 'enum',
    values: [
      { value: 'all', label: '全部' },
      { value: 'one-at-a-time', label: '逐个处理' },
    ],
    defaultValue: 'one-at-a-time',
  },
  {
    key: 'followUpMode',
    label: '后续模式',
    description: '一轮完成后如何处理后续消息',
    type: 'enum',
    values: [
      { value: 'all', label: '全部' },
      { value: 'one-at-a-time', label: '逐个处理' },
    ],
    defaultValue: 'one-at-a-time',
  },
  {
    key: 'interruptMode',
    label: '中断模式',
    description: '引导消息何时中断工具执行',
    type: 'enum',
    values: [
      { value: 'immediate', label: '立即' },
      { value: 'wait', label: '等待' },
    ],
    defaultValue: 'immediate',
  },
  {
    key: 'loop.mode',
    label: '循环模式',
    description: '/loop 迭代之间的操作',
    type: 'enum',
    values: [
      { value: 'prompt', label: '提示', description: '作为后续消息重新提交提示' },
      { value: 'compact', label: '压缩', description: '压缩会话上下文后重新提交' },
      { value: 'reset', label: '重置', description: '开始新会话后重新提交' },
    ],
    defaultValue: 'prompt',
  },
  {
    key: 'treeFilterMode',
    label: '会话树过滤',
    description: '打开会话树时的默认过滤模式',
    type: 'enum',
    values: [
      { value: 'default', label: '默认' },
      { value: 'no-tools', label: '无工具' },
      { value: 'user-only', label: '仅用户' },
      { value: 'labeled-only', label: '仅标记' },
      { value: 'all', label: '全部' },
    ],
    defaultValue: 'default',
  },
  {
    key: 'autocompleteMaxVisible',
    label: '自动完成项数',
    description: '自动完成下拉菜单中最大可见项数（3-20）',
    type: 'enum',
    values: [
      { value: '3', label: '3 项' },
      { value: '5', label: '5 项' },
      { value: '7', label: '7 项' },
      { value: '10', label: '10 项' },
      { value: '15', label: '15 项' },
      { value: '20', label: '20 项' },
    ],
    defaultValue: 5,
  },
  {
    key: 'paste.largeMenuThreshold',
    label: '大粘贴菜单阈值',
    description: '粘贴达到此行数时提供菜单（0=禁用）',
    type: 'enum',
    values: [
      { value: '0', label: '禁用' },
      { value: '100', label: '100 行' },
      { value: '250', label: '250 行' },
      { value: '500', label: '500 行' },
      { value: '1000', label: '1000 行' },
    ],
    defaultValue: 100,
  },
  {
    key: 'marketplace.autoUpdate',
    label: '插件自动更新',
    description: '启动时检查插件更新',
    type: 'enum',
    values: [
      { value: 'off', label: '关闭', description: '不检查插件更新' },
      { value: 'notify', label: '通知', description: '启动检查并通知有更新' },
      { value: 'auto', label: '自动', description: '启动检查并自动安装更新' },
    ],
    defaultValue: 'notify',
  },
  {
    key: 'magicKeywords.enabled',
    label: '魔法关键词',
    description: '启用 ultrathink、orchestrate、workflowz 关键词隐藏通知',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'completion.notify',
    label: '完成通知',
    description: '代理完成一轮时通知',
    type: 'enum',
    values: [
      { value: 'on', label: '开启' },
      { value: 'off', label: '关闭' },
    ],
    defaultValue: 'on',
  },
  {
    key: 'ask.timeout',
    label: 'Ask 超时',
    description: '自动选择推荐 ask 选项前的秒数（0=禁用）',
    type: 'enum',
    values: [
      { value: '0', label: '禁用' },
      { value: '15', label: '15 秒' },
      { value: '30', label: '30 秒' },
      { value: '60', label: '60 秒' },
      { value: '120', label: '120 秒' },
    ],
    defaultValue: 0,
  },
  {
    key: 'ask.notify',
    label: 'Ask 通知',
    description: 'ask 工具等待输入时通知',
    type: 'enum',
    values: [
      { value: 'on', label: '开启' },
      { value: 'off', label: '关闭' },
    ],
    defaultValue: 'on',
  },
  {
    key: 'autoResume',
    label: '自动恢复',
    description: '在当前目录自动恢复最近的会话',
    type: 'boolean',
    defaultValue: false,
  },

  // ==================== 上下文 ====================
  {
    key: 'contextPromotion.enabled',
    label: '自动提升上下文',
    description: '上下文溢出时提升到大上下文模型而非压缩',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'compaction.enabled',
    label: '自动压缩',
    description: '上下文过大时自动压缩',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'compaction.strategy',
    label: '压缩策略',
    description: '选择压缩策略',
    type: 'enum',
    values: [
      { value: 'context-full', label: 'Context-full', description: '原地总结并保持当前会话' },
      { value: 'handoff', label: 'Handoff', description: '生成交接文档并在新会话继续' },
      { value: 'shake', label: 'Shake', description: '原地丢弃重内容，可通过 artifact 恢复' },
      { value: 'snapcompact', label: 'Snapcompact', description: '将历史归档为密集位图图像' },
      { value: 'off', label: '关闭', description: '禁用自动上下文维护' },
    ],
    defaultValue: 'context-full',
  },
  {
    key: 'compaction.thresholdPercent',
    label: '压缩阈值',
    description: '上下文维护的百分比阈值',
    type: 'enum',
    values: [
      { value: 'default', label: '默认', description: '基于预留的旧版阈值' },
      { value: '10', label: '10%', description: '极早维护' },
      { value: '20', label: '20%', description: '很早维护' },
      { value: '30', label: '30%', description: '早维护' },
      { value: '50', label: '50%', description: '中间点' },
      { value: '70', label: '70%', description: '适中上下文使用' },
      { value: '80', label: '80%', description: '典型阈值' },
      { value: '90', label: '90%', description: '非常激进' },
      { value: '95', label: '95%', description: '接近上下文限制' },
    ],
    defaultValue: -1,
  },
  {
    key: 'compaction.handoffSaveToDisk',
    label: '保存交接文档',
    description: '将生成的交接文档保存为 markdown 文件',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'compaction.remoteEnabled',
    label: '远程压缩',
    description: '可用时使用远程压缩端点而非本地总结',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'compaction.idleEnabled',
    label: '空闲压缩',
    description: '空闲时当 token 数超过阈值压缩上下文',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'compaction.idleThresholdTokens',
    label: '空闲压缩阈值',
    description: '触发空闲压缩的 token 数阈值',
    type: 'enum',
    values: [
      { value: '100000', label: '100K tokens' },
      { value: '200000', label: '200K tokens' },
      { value: '300000', label: '300K tokens' },
      { value: '500000', label: '500K tokens' },
      { value: '700000', label: '700K tokens' },
    ],
    defaultValue: 200000,
  },
  {
    key: 'compaction.idleTimeoutSeconds',
    label: '空闲压缩延迟',
    description: '空闲多少秒后开始压缩',
    type: 'enum',
    values: [
      { value: '60', label: '1 分钟' },
      { value: '120', label: '2 分钟' },
      { value: '300', label: '5 分钟' },
      { value: '600', label: '10 分钟' },
      { value: '1800', label: '30 分钟' },
      { value: '3600', label: '1 小时' },
    ],
    defaultValue: 300,
  },
  {
    key: 'compaction.supersedeReads',
    label: '替换陈旧读取',
    description: '再次读取同一文件时清理旧的读取结果',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'compaction.dropUseless',
    label: '删除无用结果',
    description: '消耗后清理标记为无用的工具结果',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'branchSummary.enabled',
    label: '分支总结',
    description: '离开分支时提示总结',
    type: 'boolean',
    defaultValue: false,
  },

  // ==================== 文件 ====================
  {
    key: 'edit.mode',
    label: '编辑模式',
    description: '选择编辑工具变体',
    type: 'enum',
    values: [
      { value: 'hashline', label: 'Hashline' },
      { value: 'replace', label: 'Replace' },
      { value: 'patch', label: 'Patch' },
      { value: 'apply_patch', label: 'Apply Patch' },
    ],
    defaultValue: 'hashline',
  },
  {
    key: 'edit.fuzzyMatch',
    label: '模糊匹配',
    description: '接受高置信度模糊匹配处理空白差异',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'edit.fuzzyThreshold',
    label: '模糊匹配阈值',
    description: '接受模糊匹配的相似度阈值（0-1）',
    type: 'enum',
    values: [
      { value: '0.85', label: '0.85', description: '宽松' },
      { value: '0.90', label: '0.90', description: '适中' },
      { value: '0.95', label: '0.95', description: '默认' },
      { value: '0.98', label: '0.98', description: '严格' },
    ],
    defaultValue: 0.95,
  },
  {
    key: 'edit.streamingAbort',
    label: '预览失败时中止',
    description: '补丁预览失败时中止流式编辑工具调用',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'edit.blockAutoGenerated',
    label: '阻止自动生成文件',
    description: '防止编辑看起来是自动生成的文件',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'readLineNumbers',
    label: '行号',
    description: '默认在读取工具输出中添加行号',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'readHashLines',
    label: 'Hash 行',
    description: '在读取输出中包含快照标记头和行号',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'read.defaultLimit',
    label: '默认读取限制',
    description: '代理调用 read 时返回的默认行数',
    type: 'enum',
    values: [
      { value: '200', label: '200 行' },
      { value: '300', label: '300 行' },
      { value: '500', label: '500 行' },
      { value: '1000', label: '1000 行' },
      { value: '5000', label: '5000 行' },
    ],
    defaultValue: 300,
  },
  {
    key: 'read.summarize.enabled',
    label: '读取总结',
    description: '无显式选择器时返回结构化代码总结',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'read.summarize.prose',
    label: '文本总结',
    description: '对 Markdown 和纯文本返回结构化总结',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'read.toolResultPreview',
    label: '内联读取预览',
    description: '在对话中内联渲染读取工具结果',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'lsp.enabled',
    label: 'LSP',
    description: '启用 lsp 工具进行代码智能',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'lsp.lazy',
    label: '延迟 LSP 启动',
    description: '首次使用时启动语言服务器而非启动时',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'lsp.formatOnWrite',
    label: '写入时格式化',
    description: '写入后使用 LSP 自动格式化代码文件',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'lsp.diagnosticsOnWrite',
    label: '写入时诊断',
    description: '写入代码文件后返回 LSP 诊断',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'lsp.diagnosticsOnEdit',
    label: '编辑时诊断',
    description: '编辑代码文件后返回 LSP 诊断',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'lsp.diagnosticsDeduplicate',
    label: '去重诊断',
    description: '抑制文件已显示的后编辑 LSP 诊断',
    type: 'boolean',
    defaultValue: true,
  },

  // ==================== Shell ====================
  {
    key: 'bash.enabled',
    label: 'Bash',
    description: '启用 bash 工具执行 shell 命令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'bash.autoBackground.enabled',
    label: 'Bash 自动后台',
    description: '自动将长时间运行的 bash 命令后台化',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'bashInterceptor.enabled',
    label: 'Bash 拦截器',
    description: '阻止有专用工具的 shell 命令',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'bash.stripTrailingHeadTail',
    label: '去除 head/tail 管道',
    description: '静默丢弃单行 bash 命令的尾部 | head/| tail 管道',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'shellMinimizer.enabled',
    label: 'Shell 简化器',
    description: '压缩冗长的 shell 输出',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'shellMinimizer.sourceOutlineLevel',
    label: 'Shell 简化器源码大纲',
    description: '源文件 cat/read 的源码大纲模式',
    type: 'enum',
    values: [
      { value: 'default', label: '默认' },
      { value: 'aggressive', label: '激进' },
    ],
    defaultValue: 'default',
  },
  {
    key: 'eval.py',
    label: 'Python Eval',
    description: '允许 eval 工具将 Python cell 分发到 IPython kernel',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'eval.js',
    label: 'JavaScript Eval',
    description: '允许 eval 工具将 JavaScript cell 分发到进程内运行时',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'python.kernelMode',
    label: 'Python Kernel 模式',
    description: '保持 IPython kernel 跨 eval 调用存活或每次重新启动',
    type: 'enum',
    values: [
      { value: 'session', label: '会话', description: '跨调用保持 kernel' },
      { value: 'per-call', label: '每次调用', description: '每次重新启动' },
    ],
    defaultValue: 'session',
  },
  {
    key: 'python.interpreter',
    label: 'Python 解释器',
    description: '可选的 Python 可执行文件路径',
    type: 'string',
    defaultValue: '',
  },

  // ==================== 工具 ====================
  {
    key: 'tools.approvalMode',
    label: '工具审批模式',
    description: '工具调用的默认审批行为',
    type: 'enum',
    values: [
      { value: 'always-ask', label: '始终询问', description: '自动批准只读工具，确认写/执行工具' },
      { value: 'write', label: '写入', description: '自动批准读写工具，确认执行工具' },
      { value: 'yolo', label: 'Yolo', description: '自动批准所有工具' },
    ],
    defaultValue: 'yolo',
  },
  {
    key: 'todo.enabled',
    label: 'Todos',
    description: '启用 todo 工具进行任务跟踪',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'todo.reminders',
    label: 'Todo 提醒',
    description: '提醒代理在停止前完成 todos',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'todo.reminders.max',
    label: 'Todo 提醒限制',
    description: '放弃前的最大 todo 提醒次数',
    type: 'enum',
    values: [
      { value: '1', label: '1 次提醒' },
      { value: '2', label: '2 次提醒' },
      { value: '3', label: '3 次提醒' },
      { value: '5', label: '5 次提醒' },
    ],
    defaultValue: 3,
  },
  {
    key: 'todo.eager',
    label: '自动创建 Todos',
    description: '首条消息后自动创建全面的 todo 列表',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'find.enabled',
    label: 'Find',
    description: '启用 find 工具进行 glob 文件查找',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'search.enabled',
    label: 'Search',
    description: '启用 search 工具进行正则内容搜索',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'search.contextBefore',
    label: '搜索前置上下文',
    description: '每个搜索匹配前的上下文行数',
    type: 'enum',
    values: [
      { value: '0', label: '0 行' },
      { value: '1', label: '1 行' },
      { value: '2', label: '2 行' },
      { value: '3', label: '3 行' },
      { value: '5', label: '5 行' },
    ],
    defaultValue: 1,
  },
  {
    key: 'search.contextAfter',
    label: '搜索后置上下文',
    description: '每个搜索匹配后的上下文行数',
    type: 'enum',
    values: [
      { value: '0', label: '0 行' },
      { value: '1', label: '1 行' },
      { value: '2', label: '2 行' },
      { value: '3', label: '3 行' },
      { value: '5', label: '5 行' },
      { value: '10', label: '10 行' },
    ],
    defaultValue: 3,
  },
  {
    key: 'astGrep.enabled',
    label: 'AST Grep',
    description: '启用 ast_grep 工具进行结构化 AST 搜索',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'astEdit.enabled',
    label: 'AST Edit',
    description: '启用 ast_edit 工具进行结构化 AST 重写',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'renderMermaid.enabled',
    label: '渲染 Mermaid',
    description: '启用 render_mermaid 工具',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'debug.enabled',
    label: 'Debug',
    description: '启用 debug 工具进行 DAP 调试',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'inspect_image.enabled',
    label: '图像检查',
    description: '启用 inspect_image 工具委托图像理解',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'checkpoint.enabled',
    label: '检查点/回退',
    description: '启用 checkpoint 和 rewind 工具进行上下文检查点',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'vault.enabled',
    label: 'Obsidian Vault',
    description: '启用 vault:// 内部 URL 读写 Obsidian vault 内容',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'github.enabled',
    label: 'GitHub CLI',
    description: '启用 github 工具',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'github.cache.enabled',
    label: 'GitHub 视图缓存',
    description: '缓存渲染的 issue/PR 视图输出',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'web_search.enabled',
    label: 'Web Search',
    description: '启用 web_search 工具获取实时 web 结果',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'browser.enabled',
    label: 'Browser',
    description: '启用 browser 工具进行 Chromium 自动化',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'browser.headless',
    label: '无头浏览器',
    description: '以无头模式启动浏览器',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'browser.cmux',
    label: 'cmux Browser',
    description: '可用 cmux socket 时使用 cmux WKWebView',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'fetch.enabled',
    label: '读取 URL',
    description: '允许 read 工具获取和处理 URL',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'tools.intentTracing',
    label: '意图追踪',
    description: '执行前让代理描述每个工具调用的意图',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'tools.maxTimeout',
    label: '最大工具超时',
    description: '代理可为任何工具设置的最大超时秒数（0=无限制）',
    type: 'enum',
    values: [
      { value: '0', label: '无限制' },
      { value: '30', label: '30 秒' },
      { value: '60', label: '60 秒' },
      { value: '120', label: '120 秒' },
      { value: '300', label: '5 分钟' },
      { value: '600', label: '10 分钟' },
    ],
    defaultValue: 0,
  },
  {
    key: 'async.enabled',
    label: '异步执行',
    description: '启用异步 bash 命令和后台任务执行',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'async.pollWaitDuration',
    label: '最大轮询时间',
    description: 'poll 工具等待后台任务更新的时间',
    type: 'enum',
    values: [
      { value: '5s', label: '5 秒' },
      { value: '10s', label: '10 秒' },
      { value: '30s', label: '30 秒' },
      { value: '1m', label: '1 分钟' },
      { value: '5m', label: '5 分钟' },
      { value: 'smart', label: '智能', description: '自适应 5s→5m' },
    ],
    defaultValue: 'smart',
  },
  {
    key: 'tools.discoveryMode',
    label: '工具发现',
    description: '隐藏工具以节省 token',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: '超过 40 工具时隐藏 MCP 工具' },
      { value: 'off', label: '关闭', description: '不隐藏' },
      { value: 'mcp-only', label: '仅 MCP', description: '始终隐藏 MCP 工具' },
      { value: 'all', label: '全部', description: '隐藏所有非必要内置工具' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'mcp.enableProjectConfig',
    label: 'MCP 项目配置',
    description: '从项目根加载 .mcp.json/mcp.json',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'mcp.discoveryMode',
    label: 'MCP 工具发现',
    description: '默认隐藏 MCP 工具并通过发现工具暴露',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'mcp.notifications',
    label: 'MCP 更新注入',
    description: '将 MCP 资源更新注入代理对话',
    type: 'boolean',
    defaultValue: false,
  },

  // ==================== 任务 ====================
  {
    key: 'plan.enabled',
    label: '计划模式',
    description: '启用计划模式在执行前进行只读探索和规划',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'goal.enabled',
    label: '目标模式',
    description: '启用每会话目标模式和隐藏的 goal 工具',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'goal.statusInFooter',
    label: '页脚显示目标状态',
    description: '在状态栏中显示 token 预算',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'task.isolation.mode',
    label: '隔离模式',
    description: '子代理的隔离后端',
    type: 'enum',
    values: [
      { value: 'none', label: '无', description: '无隔离' },
      { value: 'auto', label: '自动', description: 'PAL 选择最佳后端' },
      { value: 'apfs', label: 'APFS', description: 'macOS clonefile reflink' },
      { value: 'btrfs', label: 'btrfs', description: 'btrfs 子卷快照' },
      { value: 'zfs', label: 'ZFS', description: 'ZFS 快照 + 克隆' },
      { value: 'reflink', label: 'Reflink', description: 'Linux FICLONE 每文件 reflink' },
      { value: 'overlayfs', label: 'Overlayfs', description: 'Linux overlay' },
      { value: 'projfs', label: 'ProjFS', description: 'Windows Projected FS' },
      { value: 'rcopy', label: '递归复制', description: 'git worktree 或递归复制' },
    ],
    defaultValue: 'none',
  },
  {
    key: 'task.isolation.merge',
    label: '隔离合并策略',
    description: '如何集成隔离任务更改',
    type: 'enum',
    values: [
      { value: 'patch', label: 'Patch', description: '合并差异并 git apply' },
      { value: 'branch', label: '分支', description: '每任务提交，用 --no-ff 合并' },
    ],
    defaultValue: 'patch',
  },
  {
    key: 'task.isolation.commits',
    label: '隔离提交风格',
    description: '嵌套仓库更改的提交消息风格',
    type: 'enum',
    values: [
      { value: 'generic', label: '通用', description: '静态提交消息' },
      { value: 'ai', label: 'AI', description: '从差异 AI 生成提交消息' },
    ],
    defaultValue: 'generic',
  },
  {
    key: 'task.eager',
    label: '优先任务委托',
    description: '鼓励代理将工作委托给子代理',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'task.batch',
    label: '批量任务调用',
    description: '将任务工具切换到批量模式',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'task.maxConcurrency',
    label: '最大并发任务',
    description: '同时运行的子代理最大数量',
    type: 'enum',
    values: [
      { value: '0', label: '无限制' },
      { value: '1', label: '1 任务' },
      { value: '2', label: '2 任务' },
      { value: '4', label: '4 任务' },
      { value: '8', label: '8 任务' },
      { value: '16', label: '16 任务' },
      { value: '32', label: '32 任务' },
      { value: '64', label: '64 任务' },
    ],
    defaultValue: 32,
  },
  {
    key: 'task.enableLsp',
    label: '子代理 LSP',
    description: '允许子代理使用 lsp 工具',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'task.maxRecursionDepth',
    label: '最大任务递归',
    description: '子代理可生成自己的子代理的深度层级',
    type: 'enum',
    values: [
      { value: '-1', label: '无限制' },
      { value: '0', label: '无' },
      { value: '1', label: '单层' },
      { value: '2', label: '双层' },
      { value: '3', label: '三层' },
    ],
    defaultValue: 2,
  },
  {
    key: 'task.maxRuntimeMs',
    label: '最大子代理运行时间',
    description: '每个子代理的硬性时钟限制（毫秒）',
    type: 'enum',
    values: [
      { value: '0', label: '无限制', description: '默认' },
      { value: '300000', label: '5 分钟' },
      { value: '900000', label: '15 分钟' },
      { value: '1800000', label: '30 分钟' },
      { value: '3600000', label: '1 小时' },
    ],
    defaultValue: 0,
  },
  {
    key: 'task.softRequestBudget',
    label: '软子代理请求预算',
    description: '每个子代理的软请求预算',
    type: 'enum',
    values: [
      { value: '0', label: '禁用' },
      { value: '40', label: '40 请求' },
      { value: '90', label: '90 请求', description: '默认' },
      { value: '150', label: '150 请求' },
    ],
    defaultValue: 90,
  },
  {
    key: 'tasks.todoClearDelay',
    label: 'Todo 自动清除延迟',
    description: '完成或放弃的 todos 被移除前的延迟秒数',
    type: 'enum',
    values: [
      { value: '0', label: '立即' },
      { value: '60', label: '1 分钟', description: '默认' },
      { value: '300', label: '5 分钟' },
      { value: '900', label: '15 分钟' },
      { value: '1800', label: '30 分钟' },
      { value: '3600', label: '1 小时' },
      { value: '-1', label: '从不' },
    ],
    defaultValue: 60,
  },
  {
    key: 'skills.enableSkillCommands',
    label: '技能命令',
    description: '将技能注册为 /skill:name 命令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'commands.enableClaudeUser',
    label: 'Claude 用户命令',
    description: '从 ~/.claude/commands/ 加载命令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'commands.enableClaudeProject',
    label: 'Claude 项目命令',
    description: '从 .claude/commands/ 加载命令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'commands.enableOpencodeUser',
    label: 'OpenCode 用户命令',
    description: '从 ~/.config/opencode/commands/ 加载命令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'commands.enableOpencodeProject',
    label: 'OpenCode 项目命令',
    description: '从 .opencode/commands/ 加载命令',
    type: 'boolean',
    defaultValue: true,
  },

  // ==================== 提供商 ====================
  {
    key: 'secrets.enabled',
    label: '隐藏密钥',
    description: '发送给 AI 提供商前混淆密钥',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'providers.webSearch',
    label: 'Web 搜索提供商',
    description: 'web_search 工具的首选提供商',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动' },
      { value: 'google', label: 'Google' },
      { value: 'duckduckgo', label: 'DuckDuckGo' },
      { value: 'tavily', label: 'Tavily' },
      { value: 'brave', label: 'Brave' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'providers.image',
    label: '图像提供商',
    description: '图像生成的首选提供商',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: 'GPT > Antigravity > xAI > OpenRouter > Gemini' },
      { value: 'openai', label: 'OpenAI' },
      { value: 'antigravity', label: 'Antigravity' },
      { value: 'xai', label: 'xAI Grok' },
      { value: 'gemini', label: 'Gemini' },
      { value: 'openrouter', label: 'OpenRouter' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'providers.tts',
    label: 'TTS 提供商',
    description: 'tts 工具后端',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: '优先本地 TTS，.mp3 输出到 xAI' },
      { value: 'local', label: '本地', description: '本地 Kokoro-82M' },
      { value: 'xai', label: 'xAI Grok Voice' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'tts.localModel',
    label: '本地 TTS 模型',
    description: '本地神经 TTS 模型',
    type: 'enum',
    values: [
      { value: 'kokoro-82m', label: 'Kokoro-82M' },
    ],
    defaultValue: 'kokoro-82m',
  },
  {
    key: 'providers.tinyModel',
    label: '小模型',
    description: '会话标题生成模型',
    type: 'enum',
    values: [
      { value: 'online-pi-smol', label: '在线 pi/smol', description: '默认' },
      { value: 'local-pi-smol', label: '本地 pi/smol' },
    ],
    defaultValue: 'online-pi-smol',
  },
  {
    key: 'providers.tinyModelDevice',
    label: '小模型设备',
    description: '本地小模型的 ONNX 执行提供商',
    type: 'enum',
    values: [
      { value: 'cpu', label: 'CPU' },
      { value: 'cuda', label: 'CUDA' },
      { value: 'coreml', label: 'CoreML' },
      { value: 'metal', label: 'Metal' },
      { value: 'rocm', label: 'ROCm' },
      { value: 'directml', label: 'DirectML' },
      { value: 'vulkan', label: 'Vulkan' },
      { value: 'openvino', label: 'OpenVINO' },
      { value: 'nnapi', label: 'NNAPI' },
      { value: 'xnnpack', label: 'XNNPACK' },
      { value: 'auto', label: '自动' },
    ],
    defaultValue: 'cpu',
  },
  {
    key: 'providers.tinyModelDtype',
    label: '小模型精度',
    description: '本地小模型的 ONNX 量化/精度',
    type: 'enum',
    values: [
      { value: 'q4', label: 'q4', description: '默认' },
      { value: 'q8', label: 'q8' },
      { value: 'f16', label: 'f16' },
      { value: 'f32', label: 'f32' },
    ],
    defaultValue: 'q4',
  },
  {
    key: 'providers.kimiApiFormat',
    label: 'Kimi API 格式',
    description: 'Kimi Code 提供商的 API 格式',
    type: 'enum',
    values: [
      { value: 'openai', label: 'OpenAI', description: 'api.kimi.com' },
      { value: 'anthropic', label: 'Anthropic', description: 'api.moonshot.ai' },
    ],
    defaultValue: 'anthropic',
  },
  {
    key: 'providers.openaiWebsockets',
    label: 'OpenAI WebSocket',
    description: 'OpenAI Codex 模型的 WebSocket 策略',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: '使用模型/提供商默认' },
      { value: 'off', label: '关闭', description: '禁用 WebSocket' },
      { value: 'on', label: '开启', description: '强制 WebSocket' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'providers.openrouterVariant',
    label: 'OpenRouter 路由',
    description: 'OpenRouter 模型 ID 的默认路由变体后缀',
    type: 'enum',
    values: [
      { value: 'default', label: '默认', description: '无后缀' },
      { value: 'nitro', label: ':nitro', description: '优先吞吐/最低延迟' },
      { value: 'floor', label: ':floor', description: '优先最便宜提供商' },
      { value: 'online', label: ':online', description: '启用 web-search 插件' },
      { value: 'exacto', label: ':exacto', description: '精选高质量提供商' },
    ],
    defaultValue: 'default',
  },
  {
    key: 'providers.fetch',
    label: 'Fetch 提供商',
    description: 'fetch/read URL 工具的读取器后端优先级',
    type: 'enum',
    values: [
      { value: 'auto', label: '自动', description: 'native > trafilatura > lynx > parallel > jina' },
      { value: 'native', label: 'Native', description: '进程内 HTML→Markdown' },
      { value: 'trafilatura', label: 'Trafilatura' },
      { value: 'lynx', label: 'Lynx' },
      { value: 'parallel', label: 'Parallel' },
      { value: 'jina', label: 'Jina' },
    ],
    defaultValue: 'auto',
  },
  {
    key: 'codexResets.autoRedeem',
    label: 'Codex 自动兑换',
    description: '当被 Codex 周限制阻塞时运行保守的保存重置检查',
    type: 'enum',
    values: [
      { value: 'unset', label: '未设置', description: '检查资格后询问' },
      { value: 'yes', label: '是', description: '无需提示花费符合条件的重置' },
      { value: 'no', label: '否', description: '不运行保存重置检查' },
    ],
    defaultValue: 'unset',
  },

  // ==================== 记忆 ====================
  {
    key: 'memory.backend',
    label: '记忆后端',
    description: '记忆子系统选择',
    type: 'enum',
    values: [
      { value: 'off', label: '关闭', description: '无记忆子系统' },
      { value: 'local', label: '本地', description: '本地 rollout 总结管道' },
      { value: 'hindsight', label: 'Hindsight', description: 'Vectorize Hindsight 远程记忆服务' },
      { value: 'mnemopi', label: 'Mnemopi', description: '本地 SQLite 回忆/保留后端' },
    ],
    defaultValue: 'off',
  },
  {
    key: 'mnemopi.scoping',
    label: 'Mnemopi 范围',
    description: '记忆范围策略',
    type: 'enum',
    values: [
      { value: 'global', label: '全局', description: '一个共享的 Mnemopi bank' },
      { value: 'per-project', label: '按项目', description: '每个 cwd 的项目本地 bank' },
      { value: 'per-project-tagged', label: '按项目（标记）', description: '写入项目本地 bank 但合并项目 + 共享回忆结果' },
    ],
    defaultValue: 'per-project',
  },
  {
    key: 'mnemopi.embeddingVariant',
    label: '嵌入变体',
    description: '本地嵌入模型家族',
    type: 'enum',
    values: [
      { value: 'en', label: '英语', description: 'bge-base-en-v1.5 (768d)' },
      { value: 'multilingual', label: '多语言', description: 'multilingual-e5-large (1024d)' },
    ],
    defaultValue: 'en',
  },
  {
    key: 'mnemopi.autoRecall',
    label: 'Mnemopi 自动回忆',
    description: '每会话第一轮回忆本地记忆',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'mnemopi.autoRetain',
    label: 'Mnemopi 自动保留',
    description: '将完成的对话轮次保留到本地 Mnemopi 记忆',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'mnemopi.polyphonicRecall',
    label: '多声回忆',
    description: '启用 4 声回忆融合',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'mnemopi.enhancedRecall',
    label: '增强回忆',
    description: '启用分层查询结果缓存',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'mnemopi.noEmbeddings',
    label: '禁用嵌入',
    description: '强制确定性 FTS-only 回忆',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'mnemopi.llmMode',
    label: 'Mnemopi LLM 模式',
    description: '使用无 LLM、配置的小模型或远程 OpenAI 端点',
    type: 'enum',
    values: [
      { value: 'none', label: '无', description: '禁用 Mnemopi LLM 提取' },
      { value: 'smol', label: '小模型', description: '使用配置的 pi-ai 小模型' },
      { value: 'remote', label: '远程', description: '使用 Mnemopi 远程 LLM 设置' },
    ],
    defaultValue: 'smol',
  },
  {
    key: 'hindsight.scoping',
    label: 'Hindsight 范围',
    description: 'Hindsight 记忆范围策略',
    type: 'enum',
    values: [
      { value: 'global', label: '全局', description: '一个共享 bank' },
      { value: 'per-project', label: '按项目', description: '每个 cwd 的隔离 bank' },
      { value: 'per-project-tagged', label: '按项目（标记）', description: '共享 bank，保留标记项目' },
    ],
    defaultValue: 'per-project-tagged',
  },
  {
    key: 'hindsight.autoRecall',
    label: 'Hindsight 自动回忆',
    description: '每会话第一轮回忆记忆',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'hindsight.autoRetain',
    label: 'Hindsight 自动保留',
    description: '每 N 轮和会话边界保留对话',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'hindsight.retainMode',
    label: 'Hindsight 保留模式',
    description: 'full-session = 每会话一个文档，last-turn = 分块',
    type: 'enum',
    values: [
      { value: 'full-session', label: '完整会话', description: '每会话 upsert 一个文档' },
      { value: 'last-turn', label: '最后一轮', description: '按轮边界分块保留' },
    ],
    defaultValue: 'full-session',
  },
  {
    key: 'hindsight.mentalModelsEnabled',
    label: 'Hindsight 心智模型',
    description: '启动时读取 curated 反思总结作为开发者指令',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'hindsight.mentalModelAutoSeed',
    label: '心智模型自动种子',
    description: '会话启动时创建 bank 上不存在的内置心智模型',
    type: 'boolean',
    defaultValue: true,
  },

  // ==================== 工具输出限制 ====================
  {
    key: 'tools.artifactSpillThreshold',
    label: 'Artifact 溢出阈值',
    description: '超过此大小的工具输出保存为 artifact（KB）',
    type: 'enum',
    values: [
      { value: '10', label: '10 KB' },
      { value: '20', label: '20 KB' },
      { value: '50', label: '50 KB', description: '默认' },
      { value: '75', label: '75 KB' },
      { value: '100', label: '100 KB' },
      { value: '200', label: '200 KB' },
      { value: '500', label: '500 KB' },
      { value: '1000', label: '1 MB' },
    ],
    defaultValue: 50,
  },
  {
    key: 'tools.artifactTailBytes',
    label: 'Artifact 尾部大小',
    description: '输出溢出到 artifact 时保持内联的尾部内容量（KB）',
    type: 'enum',
    values: [
      { value: '5', label: '5 KB' },
      { value: '10', label: '10 KB' },
      { value: '20', label: '20 KB', description: '默认' },
      { value: '50', label: '50 KB' },
      { value: '100', label: '100 KB' },
    ],
    defaultValue: 20,
  },
  {
    key: 'tools.artifactHeadBytes',
    label: 'Artifact 头部大小',
    description: '输出溢出时与尾部一起保持内联的头部内容量（KB，0=禁用）',
    type: 'enum',
    values: [
      { value: '0', label: '0 KB', description: '禁用，仅尾部截断' },
      { value: '5', label: '5 KB' },
      { value: '10', label: '10 KB' },
      { value: '20', label: '20 KB', description: '默认' },
      { value: '50', label: '50 KB' },
    ],
    defaultValue: 20,
  },
  {
    key: 'tools.outputMaxColumns',
    label: '输出列上限',
    description: '流式工具输出的每行字节上限（0=禁用）',
    type: 'enum',
    values: [
      { value: '0', label: '关闭', description: '无每行上限' },
      { value: '256', label: '256' },
      { value: '512', label: '512' },
      { value: '768', label: '768', description: '默认' },
      { value: '1024', label: '1024' },
      { value: '2048', label: '2048' },
      { value: '4096', label: '4096' },
    ],
    defaultValue: 768,
  },
  {
    key: 'tools.artifactTailLines',
    label: 'Artifact 尾部行数',
    description: '输出溢出到 artifact 时保持内联的最大尾部行数',
    type: 'enum',
    values: [
      { value: '50', label: '50 行' },
      { value: '100', label: '100 行' },
      { value: '250', label: '250 行' },
      { value: '500', label: '500 行', description: '默认' },
      { value: '1000', label: '1000 行' },
      { value: '2000', label: '2000 行' },
      { value: '5000', label: '5000 行' },
    ],
    defaultValue: 500,
  },

  // ==================== macOS 电源 ====================
  {
    key: 'power.preventIdleSleep',
    label: '防止空闲休眠',
    description: '会话打开时保持系统唤醒（caffeinate -i）',
    type: 'boolean',
    defaultValue: true,
  },
  {
    key: 'power.preventSystemSleep',
    label: 'AC 时防止系统休眠',
    description: 'AC 电源时阻止所有系统休眠（caffeinate -s）',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'power.declareUserActive',
    label: '声明用户活跃',
    description: '保持显示器亮起并将用户视为活跃（caffeinate -u）',
    type: 'boolean',
    defaultValue: false,
  },
  {
    key: 'power.preventDisplaySleep',
    label: '防止显示器休眠',
    description: '会话打开时防止显示器空闲休眠（caffeinate -d）',
    type: 'boolean',
    defaultValue: false,
  },
]

/**
 * 根据配置键获取配置项定义
 */
export function getConfigDef(key: string): ConfigItemDef | undefined {
  return OMP_CONFIG_DEFINITIONS.find(def => def.key === key)
}

/**
 * 根据配置键获取值选项
 */
export function getConfigValueOptions(key: string): ConfigValueOption[] {
  const def = getConfigDef(key)
  if (!def) return []
  if (def.type === 'boolean') {
    return [
      { value: 'true', label: '开启' },
      { value: 'false', label: '关闭' },
    ]
  }
  if (def.type === 'enum' && def.values) {
    return def.values
  }
  return []
}

/**
 * 配置键分组（用于下拉选项分组显示）
 */
export const CONFIG_KEY_GROUPS = [
  { label: '核心', keys: ['model.active', 'omp.flags.approval-mode', 'omp.flags.thinking', 'omp.flags.tools', 'vault.apiKey'] },
  { label: '模型', keys: ['defaultThinkingLevel', 'hideThinkingBlock', 'repeatToolDescriptions', 'includeModelInPrompt', 'temperature', 'topP', 'topK', 'minP', 'presencePenalty', 'repetitionPenalty', 'serviceTier', 'fastModeScope', 'retry.maxRetries', 'retry.modelFallback', 'retry.fallbackRevertPolicy'] },
  { label: '交互', keys: ['steeringMode', 'followUpMode', 'interruptMode', 'loop.mode', 'treeFilterMode', 'autocompleteMaxVisible', 'paste.largeMenuThreshold', 'marketplace.autoUpdate', 'magicKeywords.enabled', 'completion.notify', 'ask.timeout', 'ask.notify', 'autoResume'] },
  { label: '上下文', keys: ['contextPromotion.enabled', 'compaction.enabled', 'compaction.strategy', 'compaction.thresholdPercent', 'compaction.handoffSaveToDisk', 'compaction.remoteEnabled', 'compaction.idleEnabled', 'compaction.idleThresholdTokens', 'compaction.idleTimeoutSeconds', 'compaction.supersedeReads', 'compaction.dropUseless', 'branchSummary.enabled'] },
  { label: '文件', keys: ['edit.mode', 'edit.fuzzyMatch', 'edit.fuzzyThreshold', 'edit.streamingAbort', 'edit.blockAutoGenerated', 'readLineNumbers', 'readHashLines', 'read.defaultLimit', 'read.summarize.enabled', 'read.summarize.prose', 'read.toolResultPreview', 'lsp.enabled', 'lsp.lazy', 'lsp.formatOnWrite', 'lsp.diagnosticsOnWrite', 'lsp.diagnosticsOnEdit', 'lsp.diagnosticsDeduplicate'] },
  { label: 'Shell', keys: ['bash.enabled', 'bash.autoBackground.enabled', 'bashInterceptor.enabled', 'bash.stripTrailingHeadTail', 'shellMinimizer.enabled', 'shellMinimizer.sourceOutlineLevel', 'eval.py', 'eval.js', 'python.kernelMode', 'python.interpreter'] },
  { label: '工具', keys: ['tools.approvalMode', 'todo.enabled', 'todo.reminders', 'todo.reminders.max', 'todo.eager', 'find.enabled', 'search.enabled', 'search.contextBefore', 'search.contextAfter', 'astGrep.enabled', 'astEdit.enabled', 'renderMermaid.enabled', 'debug.enabled', 'inspect_image.enabled', 'checkpoint.enabled', 'vault.enabled', 'github.enabled', 'github.cache.enabled', 'web_search.enabled', 'browser.enabled', 'browser.headless', 'browser.cmux', 'fetch.enabled', 'tools.intentTracing', 'tools.maxTimeout', 'async.enabled', 'async.pollWaitDuration', 'tools.discoveryMode', 'mcp.enableProjectConfig', 'mcp.discoveryMode', 'mcp.notifications'] },
  { label: '任务', keys: ['plan.enabled', 'goal.enabled', 'goal.statusInFooter', 'task.isolation.mode', 'task.isolation.merge', 'task.isolation.commits', 'task.eager', 'task.batch', 'task.maxConcurrency', 'task.enableLsp', 'task.maxRecursionDepth', 'task.maxRuntimeMs', 'task.softRequestBudget', 'tasks.todoClearDelay', 'skills.enableSkillCommands', 'commands.enableClaudeUser', 'commands.enableClaudeProject', 'commands.enableOpencodeUser', 'commands.enableOpencodeProject'] },
  { label: '提供商', keys: ['secrets.enabled', 'providers.webSearch', 'providers.image', 'providers.tts', 'tts.localModel', 'providers.tinyModel', 'providers.tinyModelDevice', 'providers.tinyModelDtype', 'providers.kimiApiFormat', 'providers.openaiWebsockets', 'providers.openrouterVariant', 'providers.fetch', 'codexResets.autoRedeem'] },
  { label: '记忆', keys: ['memory.backend', 'mnemopi.scoping', 'mnemopi.embeddingVariant', 'mnemopi.autoRecall', 'mnemopi.autoRetain', 'mnemopi.polyphonicRecall', 'mnemopi.enhancedRecall', 'mnemopi.noEmbeddings', 'mnemopi.llmMode', 'hindsight.scoping', 'hindsight.autoRecall', 'hindsight.autoRetain', 'hindsight.retainMode', 'hindsight.mentalModelsEnabled', 'hindsight.mentalModelAutoSeed'] },
  { label: '输出限制', keys: ['tools.artifactSpillThreshold', 'tools.artifactTailBytes', 'tools.artifactHeadBytes', 'tools.outputMaxColumns', 'tools.artifactTailLines'] },
  { label: 'macOS电源', keys: ['power.preventIdleSleep', 'power.preventSystemSleep', 'power.declareUserActive', 'power.preventDisplaySleep'] },
  { label: '外观', keys: ['symbolPreset', 'display.smoothStreaming', 'display.showTokenUsage'] },
]

