worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;
events { worker_connections 1024; }

# 顶层调度：只负责加载各业务块，具体 location 都在 conf.d/ 下分文件管理。
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # 日志格式（含请求耗时，便于调试反代性能）
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time ut=$upstream_response_time';

    access_log /var/log/nginx/access.log main;

    # 引入本工程主配置（web 前端 + java 后端 + code-server，监听 80，⚠️ 不可编辑）
    include /etc/nginx/conf.d/omp-main.conf;
    # 引入业务工程反代配置（独立 server 块，监听 8888，✅ 可编辑热加载）
    include /etc/nginx/conf.d/omp-services-locations.conf;
}
